config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :alunos
  resources :cursos
  resources :instituicaos
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html 
end

app/models/aluno.rb
class Aluno < ApplicationRecord
    belongs_to :instituicao
    belongs_to :curso
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/curso.rb
class Curso < ApplicationRecord
    has_many :aluno
    belongs_to :instituicao
end

app/models/instituicao.rb
class Instituicao < ApplicationRecord
    has_many :curso
    has_many :aluno
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno criado com sucesso.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno foi atualizado.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :nota_geral)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:show, :edit, :update, :destroy]

  # GET /cursos
  # GET /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1
  # GET /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: 'Curso criado com sucesso.' }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: 'Curso foi atualizado.' }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: 'Curso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_params
      params.require(:curso).permit(:nome, :nota_geral)
    end
end

app/controllers/instituicaos_controller.rb
class InstituicaosController < ApplicationController
  before_action :set_instituicao, only: [:show, :edit, :update, :destroy]

  # GET /instituicaos
  # GET /instituicaos.json
  def index
    @instituicaos = Instituicao.all
  end

  # GET /instituicaos/1
  # GET /instituicaos/1.json
  def show
  end

  # GET /instituicaos/new
  def new
    @instituicao = Instituicao.new
  end

  # GET /instituicaos/1/edit
  def edit
  end

  # POST /instituicaos
  # POST /instituicaos.json
  def create
    @instituicao = Instituicao.new(instituicao_params)

    respond_to do |format|
      if @instituicao.save
        format.html { redirect_to @instituicao, notice: 'Instituicao criada com sucesso.' }
        format.json { render :show, status: :created, location: @instituicao }
      else
        format.html { render :new }
        format.json { render json: @instituicao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instituicaos/1
  # PATCH/PUT /instituicaos/1.json
  def update
    respond_to do |format|
      if @instituicao.update(instituicao_params)
        format.html { redirect_to @instituicao, notice: 'Instituicao foi atualizada.' }
        format.json { render :show, status: :ok, location: @instituicao }
      else
        format.html { render :edit }
        format.json { render json: @instituicao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instituicaos/1
  # DELETE /instituicaos/1.json
  def destroy
    @instituicao.destroy
    respond_to do |format|
      format.html { redirect_to instituicaos_url, notice: 'Instituicao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instituicao
      @instituicao = Instituicao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instituicao_params
      params.require(:instituicao).permit(:nome, :nota_geral)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instituicaos_helper.rb
module InstituicaosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno, local: true) do |form| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :aluno_nome %>
  </div>

  <div class="field">
    <%= form.label :nota_geral %>
    <%= form.text_field :nota_geral, id: :aluno_nota_geral %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Nota geral</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.nota_geral %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>
<br><a href="/">Home</a>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Nota geral:</strong>
  <%= @aluno.nota_geral %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>

app/views/cursos/_form.html.erb
<%= form_with(model: curso, local: true) do |form| %>
  <% if curso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curso.errors.count, "error") %> prohibited this curso from being saved:</h2>

      <ul>
      <% curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :curso_nome %>
  </div>

  <div class="field">
    <%= form.label :nota_geral %>
    <%= form.text_field :nota_geral, id: :curso_nota_geral %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cursos/edit.html.erb
<h1>Editing Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Show', @curso %> |
<%= link_to 'Back', cursos_path %>

app/views/cursos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cursos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Nota geral</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
        <td><%= curso.nome %></td>
        <td><%= curso.nota_geral %></td>
        <td><%= link_to 'Show', curso %></td>
        <td><%= link_to 'Edit', edit_curso_path(curso) %></td>
        <td><%= link_to 'Destroy', curso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curso', new_curso_path %>
<br><a href="/">Home</a>

app/views/cursos/new.html.erb
<h1>New Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Back', cursos_path %>

app/views/cursos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @curso.nome %>
</p>

<p>
  <strong>Nota geral:</strong>
  <%= @curso.nota_geral %>
</p>

<%= link_to 'Edit', edit_curso_path(@curso) %> |
<%= link_to 'Back', cursos_path %>

app/views/instituicaos/_form.html.erb
<%= form_with(model: instituicao, local: true) do |form| %>
  <% if instituicao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instituicao.errors.count, "error") %> prohibited this instituicao from being saved:</h2>

      <ul>
      <% instituicao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :instituicao_nome %>
  </div>

  <div class="field">
    <%= form.label :nota_geral %>
    <%= form.text_field :nota_geral, id: :instituicao_nota_geral %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/instituicaos/edit.html.erb
<h1>Editing Instituicao</h1>

<%= render 'form', instituicao: @instituicao %>

<%= link_to 'Show', @instituicao %> |
<%= link_to 'Back', instituicaos_path %>

app/views/instituicaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instituicaos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Nota geral</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instituicaos.each do |instituicao| %>
      <tr>
        <td><%= instituicao.nome %></td>
        <td><%= instituicao.nota_geral %></td>
        <td><%= link_to 'Show', instituicao %></td>
        <td><%= link_to 'Edit', edit_instituicao_path(instituicao) %></td>
        <td><%= link_to 'Destroy', instituicao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instituicao', new_instituicao_path %>    
<br><a href="/">Home</a>

app/views/instituicaos/new.html.erb
<h1>New Instituicao</h1>

<%= render 'form', instituicao: @instituicao %>

<%= link_to 'Back', instituicaos_path %>

app/views/instituicaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @instituicao.nome %>
</p>

<p>
  <strong>Nota geral:</strong>
  <%= @instituicao.nota_geral %>
</p>

<%= link_to 'Edit', edit_instituicao_path(@instituicao) %> |
<%= link_to 'Back', instituicaos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://getbootstrap.com/docs/4.0/examples/cover/favicon.ico">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.0/examples/cover/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>

  <body class="text-center">

    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">Olá!</h3>
        </div>
      </header>

      <main role="main" class="inner cover">
        <h1 class="cover-heading">Consulta performance ENADE 2018 </h1>
        <p class="lead">Desafio AppProva</p>
        <p class="lead">
          <a href="/instituicaos" class="btn btn-lg btn-primary" font color = "#ff0000" >Listar</a>
          <br><div class="inner">
          <h3 class="masthead-brand">Cadastrar</h3>
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="/instituicaos">Instituicao</a>
            <a class="nav-link" href="/cursos">Curso</a>
            <a class="nav-link" href="/alunos">Aluno</a>
          </nav>
        </div>
        </p>
      </main>      
    </div>    
  </body>
</html>